
# html
title: lakca blog
description: cheat sheet of every day
keywords:
  - javascript
  - nodejs
  - front end

# site
web_root: http://longpeng.me
use_permalink: false
# site module
has_category: true
has_tag: true
has_search: true

# make
# absolute or relative path of output folder
output: dist

theme: default
# pagination of post list page
post_per_page: 10

# plugin:
share.services:
  - wechat
  - twitter
  - facebook
  - weibo